---
- hosts: all
  tasks:
        - copy: src=./files/.git-promt.sh dest=~/
        - lineinfile: dest="~/.bash_profile" state=present create=yes
        line="source ~/.git-prompt.sh"
        line="export PS1='$(__git_ps1) \W\$ '"
        
        - lineinfile: dest="/etc/profile" state=present create=yes
        line="alias vi='vim'"
        
        - lineinfile: dest="/etc/vimrc" state=present create=yes
        line="syntax on"
        line="highlight Comment ctermfg=LightCyan"
        
