---
- hosts: all
  tasks:
        - copy: 
            src=./files/.git-prompt.sh 
            dest=~
        - lineinfile: 
            dest="~/.bash_profile" 
            regexp="source ~/.git-prompt.sh"
            line="source ~/.git-prompt.sh"
            state=present
        - lineinfile: 
            dest="~/.bash_profile" 
            regexp="^export PS1*"  
            line="export PS1='\[\033[38;5;10m\]\h\[$(tput sgr0)\]\[\033[38;5;26m\]@\[$(tput sgr0)\]\[\033[38;5;214m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;9m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]:\[\033[36m\]$(__git_ps1)\[\033[0m\]\\n\\$\[$(tput sgr0)\]'"
            state=present
        - lineinfile: 
            dest="~/.bashrc"
            regexp="alias vi='vim'"
            line="alias vi='vim'"
            state=present
        - lineinfile: 
            dest="~/.bashrc"
            regexp="PROMPT_COMMAND='history -a'"
            line="PROMPT_COMMAND='history -a'"
            state=present
        - lineinfile: 
            dest="~/.bashrc" 
            regexp="export HISTIGNORE='ls:ll:history:w'"
            line="export HISTIGNORE='ls:ll:history:w'" 
            state=present
        - lineinfile: 
            dest="~/.gitconfig" 
            regexp="^\[color\]"
            line="[color]"
            state=present
        - lineinfile:
            dest="~/.gitconfig"
            regexp="ui=auto"
            line="\tui=auto"
            state=present

